/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.10.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QLineEdit *LIneEdit_Result;
    QComboBox *ComboBox_Set_R1;
    QLabel *Label_Set_R1;
    QLabel *Label_Start_R1;
    QComboBox *ComboBox_Start_R1;
    QGroupBox *PlugBoard;
    QComboBox *comboBox_PB_5_2;
    QComboBox *comboBox_PB_4_2;
    QComboBox *comboBox_PB_3_2;
    QComboBox *comboBox_PB_2_2;
    QComboBox *comboBox_PB_4_1;
    QComboBox *comboBox_PB_1_1;
    QComboBox *comboBox_PB_3_1;
    QComboBox *comboBox_PB_2_1;
    QComboBox *comboBox_PB_1_2;
    QComboBox *comboBox_PB_5_1;
    QLabel *label_3;
    QLabel *label_Nome;
    QLabel *label_Logo;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QGroupBox *groupBox;
    QPushButton *Btn_A;
    QPushButton *Btn_O;
    QPushButton *Btn_I;
    QPushButton *Btn_U;
    QPushButton *Btn_Z;
    QPushButton *Btn_T;
    QPushButton *Btn_R;
    QPushButton *Btn_E;
    QPushButton *Btn_W;
    QPushButton *Btn_Q;
    QPushButton *Btn_S;
    QPushButton *Btn_D;
    QPushButton *Btn_F;
    QPushButton *Btn_G;
    QPushButton *Btn_H;
    QPushButton *Btn_J;
    QPushButton *Btn_K;
    QPushButton *Btn_P;
    QPushButton *Btn_Y;
    QPushButton *Btn_X;
    QPushButton *Btn_C;
    QPushButton *Btn_V;
    QPushButton *Btn_B;
    QPushButton *Btn_N;
    QPushButton *Btn_M;
    QPushButton *Btn_L;
    QComboBox *ComboBox_Set_R2;
    QComboBox *ComboBox_Start_R2;
    QLabel *Label_Set_R2;
    QLabel *Label_Start_R2;
    QLabel *Label_Start_R3;
    QComboBox *ComboBox_Set_R3;
    QComboBox *ComboBox_Start_R3;
    QLabel *Label_Set_R3;
    QComboBox *ComboBox_R3;
    QComboBox *ComboBox_R2;
    QComboBox *ComboBox_R1;
    QLabel *Label_Set_R1_2;
    QLabel *Label_Set_R1_3;
    QLabel *Label_Set_R1_4;
    QPushButton *Btn_End_Cr;
    QPushButton *Btn_Reset;
    QPushButton *Btn_Save;
    QPushButton *Btn_End_DeCr;
    QLineEdit *LIneEdit_Result_2;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(930, 775);
        QFont font;
        font.setPointSize(10);
        MainWindow->setFont(font);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        LIneEdit_Result = new QLineEdit(centralWidget);
        LIneEdit_Result->setObjectName(QStringLiteral("LIneEdit_Result"));
        LIneEdit_Result->setEnabled(false);
        LIneEdit_Result->setGeometry(QRect(150, 60, 631, 41));
        QFont font1;
        font1.setPointSize(10);
        font1.setBold(true);
        font1.setWeight(75);
        LIneEdit_Result->setFont(font1);
        ComboBox_Set_R1 = new QComboBox(centralWidget);
        ComboBox_Set_R1->addItem(QString());
        ComboBox_Set_R1->addItem(QString());
        ComboBox_Set_R1->addItem(QString());
        ComboBox_Set_R1->addItem(QString());
        ComboBox_Set_R1->addItem(QString());
        ComboBox_Set_R1->addItem(QString());
        ComboBox_Set_R1->addItem(QString());
        ComboBox_Set_R1->addItem(QString());
        ComboBox_Set_R1->addItem(QString());
        ComboBox_Set_R1->addItem(QString());
        ComboBox_Set_R1->addItem(QString());
        ComboBox_Set_R1->addItem(QString());
        ComboBox_Set_R1->addItem(QString());
        ComboBox_Set_R1->addItem(QString());
        ComboBox_Set_R1->addItem(QString());
        ComboBox_Set_R1->addItem(QString());
        ComboBox_Set_R1->addItem(QString());
        ComboBox_Set_R1->addItem(QString());
        ComboBox_Set_R1->addItem(QString());
        ComboBox_Set_R1->addItem(QString());
        ComboBox_Set_R1->addItem(QString());
        ComboBox_Set_R1->addItem(QString());
        ComboBox_Set_R1->addItem(QString());
        ComboBox_Set_R1->addItem(QString());
        ComboBox_Set_R1->addItem(QString());
        ComboBox_Set_R1->addItem(QString());
        ComboBox_Set_R1->setObjectName(QStringLiteral("ComboBox_Set_R1"));
        ComboBox_Set_R1->setGeometry(QRect(130, 220, 101, 31));
        Label_Set_R1 = new QLabel(centralWidget);
        Label_Set_R1->setObjectName(QStringLiteral("Label_Set_R1"));
        Label_Set_R1->setGeometry(QRect(120, 200, 111, 21));
        Label_Set_R1->setAlignment(Qt::AlignCenter);
        Label_Start_R1 = new QLabel(centralWidget);
        Label_Start_R1->setObjectName(QStringLiteral("Label_Start_R1"));
        Label_Start_R1->setGeometry(QRect(110, 280, 141, 21));
        Label_Start_R1->setAlignment(Qt::AlignCenter);
        ComboBox_Start_R1 = new QComboBox(centralWidget);
        ComboBox_Start_R1->addItem(QString());
        ComboBox_Start_R1->addItem(QString());
        ComboBox_Start_R1->addItem(QString());
        ComboBox_Start_R1->addItem(QString());
        ComboBox_Start_R1->addItem(QString());
        ComboBox_Start_R1->addItem(QString());
        ComboBox_Start_R1->addItem(QString());
        ComboBox_Start_R1->addItem(QString());
        ComboBox_Start_R1->addItem(QString());
        ComboBox_Start_R1->addItem(QString());
        ComboBox_Start_R1->addItem(QString());
        ComboBox_Start_R1->addItem(QString());
        ComboBox_Start_R1->addItem(QString());
        ComboBox_Start_R1->addItem(QString());
        ComboBox_Start_R1->addItem(QString());
        ComboBox_Start_R1->addItem(QString());
        ComboBox_Start_R1->addItem(QString());
        ComboBox_Start_R1->addItem(QString());
        ComboBox_Start_R1->addItem(QString());
        ComboBox_Start_R1->addItem(QString());
        ComboBox_Start_R1->addItem(QString());
        ComboBox_Start_R1->addItem(QString());
        ComboBox_Start_R1->addItem(QString());
        ComboBox_Start_R1->addItem(QString());
        ComboBox_Start_R1->addItem(QString());
        ComboBox_Start_R1->addItem(QString());
        ComboBox_Start_R1->setObjectName(QStringLiteral("ComboBox_Start_R1"));
        ComboBox_Start_R1->setEnabled(true);
        ComboBox_Start_R1->setGeometry(QRect(130, 300, 101, 31));
        ComboBox_Start_R1->setEditable(false);
        PlugBoard = new QGroupBox(centralWidget);
        PlugBoard->setObjectName(QStringLiteral("PlugBoard"));
        PlugBoard->setGeometry(QRect(0, 540, 931, 181));
        comboBox_PB_5_2 = new QComboBox(PlugBoard);
        comboBox_PB_5_2->addItem(QString());
        comboBox_PB_5_2->addItem(QString());
        comboBox_PB_5_2->addItem(QString());
        comboBox_PB_5_2->addItem(QString());
        comboBox_PB_5_2->addItem(QString());
        comboBox_PB_5_2->addItem(QString());
        comboBox_PB_5_2->addItem(QString());
        comboBox_PB_5_2->addItem(QString());
        comboBox_PB_5_2->addItem(QString());
        comboBox_PB_5_2->addItem(QString());
        comboBox_PB_5_2->addItem(QString());
        comboBox_PB_5_2->addItem(QString());
        comboBox_PB_5_2->addItem(QString());
        comboBox_PB_5_2->addItem(QString());
        comboBox_PB_5_2->addItem(QString());
        comboBox_PB_5_2->addItem(QString());
        comboBox_PB_5_2->addItem(QString());
        comboBox_PB_5_2->addItem(QString());
        comboBox_PB_5_2->addItem(QString());
        comboBox_PB_5_2->addItem(QString());
        comboBox_PB_5_2->addItem(QString());
        comboBox_PB_5_2->addItem(QString());
        comboBox_PB_5_2->addItem(QString());
        comboBox_PB_5_2->addItem(QString());
        comboBox_PB_5_2->addItem(QString());
        comboBox_PB_5_2->addItem(QString());
        comboBox_PB_5_2->addItem(QString());
        comboBox_PB_5_2->setObjectName(QStringLiteral("comboBox_PB_5_2"));
        comboBox_PB_5_2->setGeometry(QRect(520, 130, 101, 21));
        comboBox_PB_4_2 = new QComboBox(PlugBoard);
        comboBox_PB_4_2->addItem(QString());
        comboBox_PB_4_2->addItem(QString());
        comboBox_PB_4_2->addItem(QString());
        comboBox_PB_4_2->addItem(QString());
        comboBox_PB_4_2->addItem(QString());
        comboBox_PB_4_2->addItem(QString());
        comboBox_PB_4_2->addItem(QString());
        comboBox_PB_4_2->addItem(QString());
        comboBox_PB_4_2->addItem(QString());
        comboBox_PB_4_2->addItem(QString());
        comboBox_PB_4_2->addItem(QString());
        comboBox_PB_4_2->addItem(QString());
        comboBox_PB_4_2->addItem(QString());
        comboBox_PB_4_2->addItem(QString());
        comboBox_PB_4_2->addItem(QString());
        comboBox_PB_4_2->addItem(QString());
        comboBox_PB_4_2->addItem(QString());
        comboBox_PB_4_2->addItem(QString());
        comboBox_PB_4_2->addItem(QString());
        comboBox_PB_4_2->addItem(QString());
        comboBox_PB_4_2->addItem(QString());
        comboBox_PB_4_2->addItem(QString());
        comboBox_PB_4_2->addItem(QString());
        comboBox_PB_4_2->addItem(QString());
        comboBox_PB_4_2->addItem(QString());
        comboBox_PB_4_2->addItem(QString());
        comboBox_PB_4_2->addItem(QString());
        comboBox_PB_4_2->setObjectName(QStringLiteral("comboBox_PB_4_2"));
        comboBox_PB_4_2->setGeometry(QRect(520, 100, 101, 21));
        comboBox_PB_3_2 = new QComboBox(PlugBoard);
        comboBox_PB_3_2->addItem(QString());
        comboBox_PB_3_2->addItem(QString());
        comboBox_PB_3_2->addItem(QString());
        comboBox_PB_3_2->addItem(QString());
        comboBox_PB_3_2->addItem(QString());
        comboBox_PB_3_2->addItem(QString());
        comboBox_PB_3_2->addItem(QString());
        comboBox_PB_3_2->addItem(QString());
        comboBox_PB_3_2->addItem(QString());
        comboBox_PB_3_2->addItem(QString());
        comboBox_PB_3_2->addItem(QString());
        comboBox_PB_3_2->addItem(QString());
        comboBox_PB_3_2->addItem(QString());
        comboBox_PB_3_2->addItem(QString());
        comboBox_PB_3_2->addItem(QString());
        comboBox_PB_3_2->addItem(QString());
        comboBox_PB_3_2->addItem(QString());
        comboBox_PB_3_2->addItem(QString());
        comboBox_PB_3_2->addItem(QString());
        comboBox_PB_3_2->addItem(QString());
        comboBox_PB_3_2->addItem(QString());
        comboBox_PB_3_2->addItem(QString());
        comboBox_PB_3_2->addItem(QString());
        comboBox_PB_3_2->addItem(QString());
        comboBox_PB_3_2->addItem(QString());
        comboBox_PB_3_2->addItem(QString());
        comboBox_PB_3_2->addItem(QString());
        comboBox_PB_3_2->setObjectName(QStringLiteral("comboBox_PB_3_2"));
        comboBox_PB_3_2->setGeometry(QRect(520, 70, 101, 21));
        comboBox_PB_2_2 = new QComboBox(PlugBoard);
        comboBox_PB_2_2->addItem(QString());
        comboBox_PB_2_2->addItem(QString());
        comboBox_PB_2_2->addItem(QString());
        comboBox_PB_2_2->addItem(QString());
        comboBox_PB_2_2->addItem(QString());
        comboBox_PB_2_2->addItem(QString());
        comboBox_PB_2_2->addItem(QString());
        comboBox_PB_2_2->addItem(QString());
        comboBox_PB_2_2->addItem(QString());
        comboBox_PB_2_2->addItem(QString());
        comboBox_PB_2_2->addItem(QString());
        comboBox_PB_2_2->addItem(QString());
        comboBox_PB_2_2->addItem(QString());
        comboBox_PB_2_2->addItem(QString());
        comboBox_PB_2_2->addItem(QString());
        comboBox_PB_2_2->addItem(QString());
        comboBox_PB_2_2->addItem(QString());
        comboBox_PB_2_2->addItem(QString());
        comboBox_PB_2_2->addItem(QString());
        comboBox_PB_2_2->addItem(QString());
        comboBox_PB_2_2->addItem(QString());
        comboBox_PB_2_2->addItem(QString());
        comboBox_PB_2_2->addItem(QString());
        comboBox_PB_2_2->addItem(QString());
        comboBox_PB_2_2->addItem(QString());
        comboBox_PB_2_2->addItem(QString());
        comboBox_PB_2_2->addItem(QString());
        comboBox_PB_2_2->setObjectName(QStringLiteral("comboBox_PB_2_2"));
        comboBox_PB_2_2->setGeometry(QRect(520, 40, 101, 21));
        comboBox_PB_4_1 = new QComboBox(PlugBoard);
        comboBox_PB_4_1->addItem(QString());
        comboBox_PB_4_1->addItem(QString());
        comboBox_PB_4_1->addItem(QString());
        comboBox_PB_4_1->addItem(QString());
        comboBox_PB_4_1->addItem(QString());
        comboBox_PB_4_1->addItem(QString());
        comboBox_PB_4_1->addItem(QString());
        comboBox_PB_4_1->addItem(QString());
        comboBox_PB_4_1->addItem(QString());
        comboBox_PB_4_1->addItem(QString());
        comboBox_PB_4_1->addItem(QString());
        comboBox_PB_4_1->addItem(QString());
        comboBox_PB_4_1->addItem(QString());
        comboBox_PB_4_1->addItem(QString());
        comboBox_PB_4_1->addItem(QString());
        comboBox_PB_4_1->addItem(QString());
        comboBox_PB_4_1->addItem(QString());
        comboBox_PB_4_1->addItem(QString());
        comboBox_PB_4_1->addItem(QString());
        comboBox_PB_4_1->addItem(QString());
        comboBox_PB_4_1->addItem(QString());
        comboBox_PB_4_1->addItem(QString());
        comboBox_PB_4_1->addItem(QString());
        comboBox_PB_4_1->addItem(QString());
        comboBox_PB_4_1->addItem(QString());
        comboBox_PB_4_1->addItem(QString());
        comboBox_PB_4_1->addItem(QString());
        comboBox_PB_4_1->setObjectName(QStringLiteral("comboBox_PB_4_1"));
        comboBox_PB_4_1->setGeometry(QRect(300, 100, 101, 21));
        comboBox_PB_1_1 = new QComboBox(PlugBoard);
        comboBox_PB_1_1->addItem(QString());
        comboBox_PB_1_1->addItem(QString());
        comboBox_PB_1_1->addItem(QString());
        comboBox_PB_1_1->addItem(QString());
        comboBox_PB_1_1->addItem(QString());
        comboBox_PB_1_1->addItem(QString());
        comboBox_PB_1_1->addItem(QString());
        comboBox_PB_1_1->addItem(QString());
        comboBox_PB_1_1->addItem(QString());
        comboBox_PB_1_1->addItem(QString());
        comboBox_PB_1_1->addItem(QString());
        comboBox_PB_1_1->addItem(QString());
        comboBox_PB_1_1->addItem(QString());
        comboBox_PB_1_1->addItem(QString());
        comboBox_PB_1_1->addItem(QString());
        comboBox_PB_1_1->addItem(QString());
        comboBox_PB_1_1->addItem(QString());
        comboBox_PB_1_1->addItem(QString());
        comboBox_PB_1_1->addItem(QString());
        comboBox_PB_1_1->addItem(QString());
        comboBox_PB_1_1->addItem(QString());
        comboBox_PB_1_1->addItem(QString());
        comboBox_PB_1_1->addItem(QString());
        comboBox_PB_1_1->addItem(QString());
        comboBox_PB_1_1->addItem(QString());
        comboBox_PB_1_1->addItem(QString());
        comboBox_PB_1_1->addItem(QString());
        comboBox_PB_1_1->setObjectName(QStringLiteral("comboBox_PB_1_1"));
        comboBox_PB_1_1->setGeometry(QRect(300, 10, 101, 21));
        comboBox_PB_3_1 = new QComboBox(PlugBoard);
        comboBox_PB_3_1->addItem(QString());
        comboBox_PB_3_1->addItem(QString());
        comboBox_PB_3_1->addItem(QString());
        comboBox_PB_3_1->addItem(QString());
        comboBox_PB_3_1->addItem(QString());
        comboBox_PB_3_1->addItem(QString());
        comboBox_PB_3_1->addItem(QString());
        comboBox_PB_3_1->addItem(QString());
        comboBox_PB_3_1->addItem(QString());
        comboBox_PB_3_1->addItem(QString());
        comboBox_PB_3_1->addItem(QString());
        comboBox_PB_3_1->addItem(QString());
        comboBox_PB_3_1->addItem(QString());
        comboBox_PB_3_1->addItem(QString());
        comboBox_PB_3_1->addItem(QString());
        comboBox_PB_3_1->addItem(QString());
        comboBox_PB_3_1->addItem(QString());
        comboBox_PB_3_1->addItem(QString());
        comboBox_PB_3_1->addItem(QString());
        comboBox_PB_3_1->addItem(QString());
        comboBox_PB_3_1->addItem(QString());
        comboBox_PB_3_1->addItem(QString());
        comboBox_PB_3_1->addItem(QString());
        comboBox_PB_3_1->addItem(QString());
        comboBox_PB_3_1->addItem(QString());
        comboBox_PB_3_1->addItem(QString());
        comboBox_PB_3_1->addItem(QString());
        comboBox_PB_3_1->setObjectName(QStringLiteral("comboBox_PB_3_1"));
        comboBox_PB_3_1->setGeometry(QRect(300, 70, 101, 21));
        comboBox_PB_2_1 = new QComboBox(PlugBoard);
        comboBox_PB_2_1->addItem(QString());
        comboBox_PB_2_1->addItem(QString());
        comboBox_PB_2_1->addItem(QString());
        comboBox_PB_2_1->addItem(QString());
        comboBox_PB_2_1->addItem(QString());
        comboBox_PB_2_1->addItem(QString());
        comboBox_PB_2_1->addItem(QString());
        comboBox_PB_2_1->addItem(QString());
        comboBox_PB_2_1->addItem(QString());
        comboBox_PB_2_1->addItem(QString());
        comboBox_PB_2_1->addItem(QString());
        comboBox_PB_2_1->addItem(QString());
        comboBox_PB_2_1->addItem(QString());
        comboBox_PB_2_1->addItem(QString());
        comboBox_PB_2_1->addItem(QString());
        comboBox_PB_2_1->addItem(QString());
        comboBox_PB_2_1->addItem(QString());
        comboBox_PB_2_1->addItem(QString());
        comboBox_PB_2_1->addItem(QString());
        comboBox_PB_2_1->addItem(QString());
        comboBox_PB_2_1->addItem(QString());
        comboBox_PB_2_1->addItem(QString());
        comboBox_PB_2_1->addItem(QString());
        comboBox_PB_2_1->addItem(QString());
        comboBox_PB_2_1->addItem(QString());
        comboBox_PB_2_1->addItem(QString());
        comboBox_PB_2_1->addItem(QString());
        comboBox_PB_2_1->setObjectName(QStringLiteral("comboBox_PB_2_1"));
        comboBox_PB_2_1->setGeometry(QRect(300, 40, 101, 21));
        comboBox_PB_1_2 = new QComboBox(PlugBoard);
        comboBox_PB_1_2->addItem(QString());
        comboBox_PB_1_2->addItem(QString());
        comboBox_PB_1_2->addItem(QString());
        comboBox_PB_1_2->addItem(QString());
        comboBox_PB_1_2->addItem(QString());
        comboBox_PB_1_2->addItem(QString());
        comboBox_PB_1_2->addItem(QString());
        comboBox_PB_1_2->addItem(QString());
        comboBox_PB_1_2->addItem(QString());
        comboBox_PB_1_2->addItem(QString());
        comboBox_PB_1_2->addItem(QString());
        comboBox_PB_1_2->addItem(QString());
        comboBox_PB_1_2->addItem(QString());
        comboBox_PB_1_2->addItem(QString());
        comboBox_PB_1_2->addItem(QString());
        comboBox_PB_1_2->addItem(QString());
        comboBox_PB_1_2->addItem(QString());
        comboBox_PB_1_2->addItem(QString());
        comboBox_PB_1_2->addItem(QString());
        comboBox_PB_1_2->addItem(QString());
        comboBox_PB_1_2->addItem(QString());
        comboBox_PB_1_2->addItem(QString());
        comboBox_PB_1_2->addItem(QString());
        comboBox_PB_1_2->addItem(QString());
        comboBox_PB_1_2->addItem(QString());
        comboBox_PB_1_2->addItem(QString());
        comboBox_PB_1_2->addItem(QString());
        comboBox_PB_1_2->setObjectName(QStringLiteral("comboBox_PB_1_2"));
        comboBox_PB_1_2->setGeometry(QRect(520, 10, 101, 21));
        comboBox_PB_5_1 = new QComboBox(PlugBoard);
        comboBox_PB_5_1->addItem(QString());
        comboBox_PB_5_1->addItem(QString());
        comboBox_PB_5_1->addItem(QString());
        comboBox_PB_5_1->addItem(QString());
        comboBox_PB_5_1->addItem(QString());
        comboBox_PB_5_1->addItem(QString());
        comboBox_PB_5_1->addItem(QString());
        comboBox_PB_5_1->addItem(QString());
        comboBox_PB_5_1->addItem(QString());
        comboBox_PB_5_1->addItem(QString());
        comboBox_PB_5_1->addItem(QString());
        comboBox_PB_5_1->addItem(QString());
        comboBox_PB_5_1->addItem(QString());
        comboBox_PB_5_1->addItem(QString());
        comboBox_PB_5_1->addItem(QString());
        comboBox_PB_5_1->addItem(QString());
        comboBox_PB_5_1->addItem(QString());
        comboBox_PB_5_1->addItem(QString());
        comboBox_PB_5_1->addItem(QString());
        comboBox_PB_5_1->addItem(QString());
        comboBox_PB_5_1->addItem(QString());
        comboBox_PB_5_1->addItem(QString());
        comboBox_PB_5_1->addItem(QString());
        comboBox_PB_5_1->addItem(QString());
        comboBox_PB_5_1->addItem(QString());
        comboBox_PB_5_1->addItem(QString());
        comboBox_PB_5_1->addItem(QString());
        comboBox_PB_5_1->setObjectName(QStringLiteral("comboBox_PB_5_1"));
        comboBox_PB_5_1->setGeometry(QRect(300, 130, 101, 21));
        label_3 = new QLabel(PlugBoard);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(430, 10, 61, 21));
        QFont font2;
        font2.setPointSize(14);
        font2.setBold(true);
        font2.setWeight(75);
        font2.setStrikeOut(true);
        label_3->setFont(font2);
        label_3->setPixmap(QPixmap(QString::fromUtf8("../../adesivi-freccia-6.png")));
        label_3->setScaledContents(true);
        label_3->setAlignment(Qt::AlignCenter);
        label_Nome = new QLabel(PlugBoard);
        label_Nome->setObjectName(QStringLiteral("label_Nome"));
        label_Nome->setGeometry(QRect(710, 60, 151, 61));
        label_Logo = new QLabel(PlugBoard);
        label_Logo->setObjectName(QStringLiteral("label_Logo"));
        label_Logo->setGeometry(QRect(20, 30, 241, 131));
        label_Logo->setPixmap(QPixmap(QString::fromUtf8("../../../Downloads/logo.png")));
        label_Logo->setScaledContents(true);
        label_8 = new QLabel(PlugBoard);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(430, 100, 61, 21));
        label_8->setFont(font2);
        label_8->setPixmap(QPixmap(QString::fromUtf8("../../adesivi-freccia-6.png")));
        label_8->setScaledContents(true);
        label_8->setAlignment(Qt::AlignCenter);
        label_9 = new QLabel(PlugBoard);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(430, 130, 61, 21));
        label_9->setFont(font2);
        label_9->setPixmap(QPixmap(QString::fromUtf8("../../adesivi-freccia-6.png")));
        label_9->setScaledContents(true);
        label_9->setAlignment(Qt::AlignCenter);
        label_10 = new QLabel(PlugBoard);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(430, 40, 61, 21));
        label_10->setFont(font2);
        label_10->setPixmap(QPixmap(QString::fromUtf8("../../adesivi-freccia-6.png")));
        label_10->setScaledContents(true);
        label_10->setAlignment(Qt::AlignCenter);
        label_11 = new QLabel(PlugBoard);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(430, 70, 61, 21));
        label_11->setFont(font2);
        label_11->setPixmap(QPixmap(QString::fromUtf8("../../adesivi-freccia-6.png")));
        label_11->setScaledContents(true);
        label_11->setAlignment(Qt::AlignCenter);
        groupBox = new QGroupBox(centralWidget);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(10, 340, 921, 201));
        Btn_A = new QPushButton(groupBox);
        Btn_A->setObjectName(QStringLiteral("Btn_A"));
        Btn_A->setEnabled(false);
        Btn_A->setGeometry(QRect(180, 70, 71, 61));
        Btn_O = new QPushButton(groupBox);
        Btn_O->setObjectName(QStringLiteral("Btn_O"));
        Btn_O->setEnabled(false);
        Btn_O->setGeometry(QRect(710, 10, 71, 61));
        Btn_I = new QPushButton(groupBox);
        Btn_I->setObjectName(QStringLiteral("Btn_I"));
        Btn_I->setEnabled(false);
        Btn_I->setGeometry(QRect(640, 10, 71, 61));
        Btn_U = new QPushButton(groupBox);
        Btn_U->setObjectName(QStringLiteral("Btn_U"));
        Btn_U->setEnabled(false);
        Btn_U->setGeometry(QRect(570, 10, 71, 61));
        Btn_Z = new QPushButton(groupBox);
        Btn_Z->setObjectName(QStringLiteral("Btn_Z"));
        Btn_Z->setEnabled(false);
        Btn_Z->setGeometry(QRect(500, 10, 71, 61));
        Btn_T = new QPushButton(groupBox);
        Btn_T->setObjectName(QStringLiteral("Btn_T"));
        Btn_T->setEnabled(false);
        Btn_T->setGeometry(QRect(430, 10, 71, 61));
        Btn_R = new QPushButton(groupBox);
        Btn_R->setObjectName(QStringLiteral("Btn_R"));
        Btn_R->setEnabled(false);
        Btn_R->setGeometry(QRect(360, 10, 71, 61));
        Btn_E = new QPushButton(groupBox);
        Btn_E->setObjectName(QStringLiteral("Btn_E"));
        Btn_E->setEnabled(false);
        Btn_E->setGeometry(QRect(290, 10, 71, 61));
        Btn_W = new QPushButton(groupBox);
        Btn_W->setObjectName(QStringLiteral("Btn_W"));
        Btn_W->setEnabled(false);
        Btn_W->setGeometry(QRect(220, 10, 71, 61));
        Btn_Q = new QPushButton(groupBox);
        Btn_Q->setObjectName(QStringLiteral("Btn_Q"));
        Btn_Q->setEnabled(false);
        Btn_Q->setGeometry(QRect(150, 10, 71, 61));
        Btn_S = new QPushButton(groupBox);
        Btn_S->setObjectName(QStringLiteral("Btn_S"));
        Btn_S->setEnabled(false);
        Btn_S->setGeometry(QRect(250, 70, 71, 61));
        Btn_D = new QPushButton(groupBox);
        Btn_D->setObjectName(QStringLiteral("Btn_D"));
        Btn_D->setEnabled(false);
        Btn_D->setGeometry(QRect(320, 70, 71, 61));
        Btn_F = new QPushButton(groupBox);
        Btn_F->setObjectName(QStringLiteral("Btn_F"));
        Btn_F->setEnabled(false);
        Btn_F->setGeometry(QRect(390, 70, 71, 61));
        Btn_G = new QPushButton(groupBox);
        Btn_G->setObjectName(QStringLiteral("Btn_G"));
        Btn_G->setEnabled(false);
        Btn_G->setGeometry(QRect(460, 70, 71, 61));
        Btn_H = new QPushButton(groupBox);
        Btn_H->setObjectName(QStringLiteral("Btn_H"));
        Btn_H->setEnabled(false);
        Btn_H->setGeometry(QRect(530, 70, 71, 61));
        Btn_J = new QPushButton(groupBox);
        Btn_J->setObjectName(QStringLiteral("Btn_J"));
        Btn_J->setEnabled(false);
        Btn_J->setGeometry(QRect(600, 70, 71, 61));
        Btn_K = new QPushButton(groupBox);
        Btn_K->setObjectName(QStringLiteral("Btn_K"));
        Btn_K->setEnabled(false);
        Btn_K->setGeometry(QRect(670, 70, 71, 61));
        Btn_P = new QPushButton(groupBox);
        Btn_P->setObjectName(QStringLiteral("Btn_P"));
        Btn_P->setEnabled(false);
        Btn_P->setGeometry(QRect(150, 130, 71, 61));
        Btn_Y = new QPushButton(groupBox);
        Btn_Y->setObjectName(QStringLiteral("Btn_Y"));
        Btn_Y->setEnabled(false);
        Btn_Y->setGeometry(QRect(220, 130, 71, 61));
        Btn_X = new QPushButton(groupBox);
        Btn_X->setObjectName(QStringLiteral("Btn_X"));
        Btn_X->setEnabled(false);
        Btn_X->setGeometry(QRect(290, 130, 71, 61));
        Btn_C = new QPushButton(groupBox);
        Btn_C->setObjectName(QStringLiteral("Btn_C"));
        Btn_C->setEnabled(false);
        Btn_C->setGeometry(QRect(360, 130, 71, 61));
        Btn_V = new QPushButton(groupBox);
        Btn_V->setObjectName(QStringLiteral("Btn_V"));
        Btn_V->setEnabled(false);
        Btn_V->setGeometry(QRect(430, 130, 71, 61));
        Btn_B = new QPushButton(groupBox);
        Btn_B->setObjectName(QStringLiteral("Btn_B"));
        Btn_B->setEnabled(false);
        Btn_B->setGeometry(QRect(500, 130, 71, 61));
        Btn_N = new QPushButton(groupBox);
        Btn_N->setObjectName(QStringLiteral("Btn_N"));
        Btn_N->setEnabled(false);
        Btn_N->setGeometry(QRect(570, 130, 71, 61));
        Btn_M = new QPushButton(groupBox);
        Btn_M->setObjectName(QStringLiteral("Btn_M"));
        Btn_M->setEnabled(false);
        Btn_M->setGeometry(QRect(640, 130, 71, 61));
        Btn_L = new QPushButton(groupBox);
        Btn_L->setObjectName(QStringLiteral("Btn_L"));
        Btn_L->setEnabled(false);
        Btn_L->setGeometry(QRect(710, 130, 71, 61));
        ComboBox_Set_R2 = new QComboBox(centralWidget);
        ComboBox_Set_R2->addItem(QString());
        ComboBox_Set_R2->addItem(QString());
        ComboBox_Set_R2->addItem(QString());
        ComboBox_Set_R2->addItem(QString());
        ComboBox_Set_R2->addItem(QString());
        ComboBox_Set_R2->addItem(QString());
        ComboBox_Set_R2->addItem(QString());
        ComboBox_Set_R2->addItem(QString());
        ComboBox_Set_R2->addItem(QString());
        ComboBox_Set_R2->addItem(QString());
        ComboBox_Set_R2->addItem(QString());
        ComboBox_Set_R2->addItem(QString());
        ComboBox_Set_R2->addItem(QString());
        ComboBox_Set_R2->addItem(QString());
        ComboBox_Set_R2->addItem(QString());
        ComboBox_Set_R2->addItem(QString());
        ComboBox_Set_R2->addItem(QString());
        ComboBox_Set_R2->addItem(QString());
        ComboBox_Set_R2->addItem(QString());
        ComboBox_Set_R2->addItem(QString());
        ComboBox_Set_R2->addItem(QString());
        ComboBox_Set_R2->addItem(QString());
        ComboBox_Set_R2->addItem(QString());
        ComboBox_Set_R2->addItem(QString());
        ComboBox_Set_R2->addItem(QString());
        ComboBox_Set_R2->addItem(QString());
        ComboBox_Set_R2->setObjectName(QStringLiteral("ComboBox_Set_R2"));
        ComboBox_Set_R2->setGeometry(QRect(300, 220, 101, 31));
        ComboBox_Start_R2 = new QComboBox(centralWidget);
        ComboBox_Start_R2->addItem(QString());
        ComboBox_Start_R2->addItem(QString());
        ComboBox_Start_R2->addItem(QString());
        ComboBox_Start_R2->addItem(QString());
        ComboBox_Start_R2->addItem(QString());
        ComboBox_Start_R2->addItem(QString());
        ComboBox_Start_R2->addItem(QString());
        ComboBox_Start_R2->addItem(QString());
        ComboBox_Start_R2->addItem(QString());
        ComboBox_Start_R2->addItem(QString());
        ComboBox_Start_R2->addItem(QString());
        ComboBox_Start_R2->addItem(QString());
        ComboBox_Start_R2->addItem(QString());
        ComboBox_Start_R2->addItem(QString());
        ComboBox_Start_R2->addItem(QString());
        ComboBox_Start_R2->addItem(QString());
        ComboBox_Start_R2->addItem(QString());
        ComboBox_Start_R2->addItem(QString());
        ComboBox_Start_R2->addItem(QString());
        ComboBox_Start_R2->addItem(QString());
        ComboBox_Start_R2->addItem(QString());
        ComboBox_Start_R2->addItem(QString());
        ComboBox_Start_R2->addItem(QString());
        ComboBox_Start_R2->addItem(QString());
        ComboBox_Start_R2->addItem(QString());
        ComboBox_Start_R2->addItem(QString());
        ComboBox_Start_R2->setObjectName(QStringLiteral("ComboBox_Start_R2"));
        ComboBox_Start_R2->setGeometry(QRect(300, 300, 101, 31));
        Label_Set_R2 = new QLabel(centralWidget);
        Label_Set_R2->setObjectName(QStringLiteral("Label_Set_R2"));
        Label_Set_R2->setGeometry(QRect(290, 200, 111, 21));
        Label_Set_R2->setAlignment(Qt::AlignCenter);
        Label_Start_R2 = new QLabel(centralWidget);
        Label_Start_R2->setObjectName(QStringLiteral("Label_Start_R2"));
        Label_Start_R2->setGeometry(QRect(280, 280, 141, 21));
        Label_Start_R2->setAlignment(Qt::AlignCenter);
        Label_Start_R3 = new QLabel(centralWidget);
        Label_Start_R3->setObjectName(QStringLiteral("Label_Start_R3"));
        Label_Start_R3->setGeometry(QRect(440, 280, 151, 21));
        Label_Start_R3->setAlignment(Qt::AlignCenter);
        ComboBox_Set_R3 = new QComboBox(centralWidget);
        ComboBox_Set_R3->addItem(QString());
        ComboBox_Set_R3->addItem(QString());
        ComboBox_Set_R3->addItem(QString());
        ComboBox_Set_R3->addItem(QString());
        ComboBox_Set_R3->addItem(QString());
        ComboBox_Set_R3->addItem(QString());
        ComboBox_Set_R3->addItem(QString());
        ComboBox_Set_R3->addItem(QString());
        ComboBox_Set_R3->addItem(QString());
        ComboBox_Set_R3->addItem(QString());
        ComboBox_Set_R3->addItem(QString());
        ComboBox_Set_R3->addItem(QString());
        ComboBox_Set_R3->addItem(QString());
        ComboBox_Set_R3->addItem(QString());
        ComboBox_Set_R3->addItem(QString());
        ComboBox_Set_R3->addItem(QString());
        ComboBox_Set_R3->addItem(QString());
        ComboBox_Set_R3->addItem(QString());
        ComboBox_Set_R3->addItem(QString());
        ComboBox_Set_R3->addItem(QString());
        ComboBox_Set_R3->addItem(QString());
        ComboBox_Set_R3->addItem(QString());
        ComboBox_Set_R3->addItem(QString());
        ComboBox_Set_R3->addItem(QString());
        ComboBox_Set_R3->addItem(QString());
        ComboBox_Set_R3->addItem(QString());
        ComboBox_Set_R3->setObjectName(QStringLiteral("ComboBox_Set_R3"));
        ComboBox_Set_R3->setGeometry(QRect(460, 220, 101, 31));
        ComboBox_Start_R3 = new QComboBox(centralWidget);
        ComboBox_Start_R3->addItem(QString());
        ComboBox_Start_R3->addItem(QString());
        ComboBox_Start_R3->addItem(QString());
        ComboBox_Start_R3->addItem(QString());
        ComboBox_Start_R3->addItem(QString());
        ComboBox_Start_R3->addItem(QString());
        ComboBox_Start_R3->addItem(QString());
        ComboBox_Start_R3->addItem(QString());
        ComboBox_Start_R3->addItem(QString());
        ComboBox_Start_R3->addItem(QString());
        ComboBox_Start_R3->addItem(QString());
        ComboBox_Start_R3->addItem(QString());
        ComboBox_Start_R3->addItem(QString());
        ComboBox_Start_R3->addItem(QString());
        ComboBox_Start_R3->addItem(QString());
        ComboBox_Start_R3->addItem(QString());
        ComboBox_Start_R3->addItem(QString());
        ComboBox_Start_R3->addItem(QString());
        ComboBox_Start_R3->addItem(QString());
        ComboBox_Start_R3->addItem(QString());
        ComboBox_Start_R3->addItem(QString());
        ComboBox_Start_R3->addItem(QString());
        ComboBox_Start_R3->addItem(QString());
        ComboBox_Start_R3->addItem(QString());
        ComboBox_Start_R3->addItem(QString());
        ComboBox_Start_R3->addItem(QString());
        ComboBox_Start_R3->setObjectName(QStringLiteral("ComboBox_Start_R3"));
        ComboBox_Start_R3->setGeometry(QRect(460, 300, 101, 31));
        Label_Set_R3 = new QLabel(centralWidget);
        Label_Set_R3->setObjectName(QStringLiteral("Label_Set_R3"));
        Label_Set_R3->setGeometry(QRect(450, 200, 111, 21));
        Label_Set_R3->setAlignment(Qt::AlignCenter);
        ComboBox_R3 = new QComboBox(centralWidget);
        ComboBox_R3->addItem(QString());
        ComboBox_R3->addItem(QString());
        ComboBox_R3->addItem(QString());
        ComboBox_R3->addItem(QString());
        ComboBox_R3->setObjectName(QStringLiteral("ComboBox_R3"));
        ComboBox_R3->setGeometry(QRect(460, 140, 101, 31));
        ComboBox_R2 = new QComboBox(centralWidget);
        ComboBox_R2->addItem(QString());
        ComboBox_R2->addItem(QString());
        ComboBox_R2->addItem(QString());
        ComboBox_R2->addItem(QString());
        ComboBox_R2->setObjectName(QStringLiteral("ComboBox_R2"));
        ComboBox_R2->setGeometry(QRect(300, 140, 101, 31));
        ComboBox_R1 = new QComboBox(centralWidget);
        ComboBox_R1->addItem(QString());
        ComboBox_R1->addItem(QString());
        ComboBox_R1->addItem(QString());
        ComboBox_R1->addItem(QString());
        ComboBox_R1->setObjectName(QStringLiteral("ComboBox_R1"));
        ComboBox_R1->setEnabled(true);
        ComboBox_R1->setGeometry(QRect(130, 140, 101, 31));
        ComboBox_R1->setLayoutDirection(Qt::LeftToRight);
        ComboBox_R1->setEditable(false);
        ComboBox_R1->setInsertPolicy(QComboBox::InsertAtBottom);
        Label_Set_R1_2 = new QLabel(centralWidget);
        Label_Set_R1_2->setObjectName(QStringLiteral("Label_Set_R1_2"));
        Label_Set_R1_2->setGeometry(QRect(130, 120, 111, 21));
        Label_Set_R1_2->setAlignment(Qt::AlignCenter);
        Label_Set_R1_3 = new QLabel(centralWidget);
        Label_Set_R1_3->setObjectName(QStringLiteral("Label_Set_R1_3"));
        Label_Set_R1_3->setGeometry(QRect(300, 120, 111, 21));
        Label_Set_R1_3->setAlignment(Qt::AlignCenter);
        Label_Set_R1_4 = new QLabel(centralWidget);
        Label_Set_R1_4->setObjectName(QStringLiteral("Label_Set_R1_4"));
        Label_Set_R1_4->setGeometry(QRect(460, 120, 111, 21));
        Label_Set_R1_4->setAlignment(Qt::AlignCenter);
        Btn_End_Cr = new QPushButton(centralWidget);
        Btn_End_Cr->setObjectName(QStringLiteral("Btn_End_Cr"));
        Btn_End_Cr->setGeometry(QRect(600, 140, 75, 191));
        Btn_Reset = new QPushButton(centralWidget);
        Btn_Reset->setObjectName(QStringLiteral("Btn_Reset"));
        Btn_Reset->setGeometry(QRect(780, 140, 81, 91));
        Btn_Save = new QPushButton(centralWidget);
        Btn_Save->setObjectName(QStringLiteral("Btn_Save"));
        Btn_Save->setGeometry(QRect(780, 240, 81, 91));
        Btn_End_DeCr = new QPushButton(centralWidget);
        Btn_End_DeCr->setObjectName(QStringLiteral("Btn_End_DeCr"));
        Btn_End_DeCr->setEnabled(false);
        Btn_End_DeCr->setGeometry(QRect(690, 140, 75, 191));
        LIneEdit_Result_2 = new QLineEdit(centralWidget);
        LIneEdit_Result_2->setObjectName(QStringLiteral("LIneEdit_Result_2"));
        LIneEdit_Result_2->setEnabled(false);
        LIneEdit_Result_2->setGeometry(QRect(150, 10, 631, 41));
        LIneEdit_Result_2->setFont(font1);
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 930, 21));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        comboBox_PB_5_2->setCurrentIndex(26);
        comboBox_PB_4_2->setCurrentIndex(26);
        comboBox_PB_3_2->setCurrentIndex(26);
        comboBox_PB_2_2->setCurrentIndex(26);
        comboBox_PB_4_1->setCurrentIndex(26);
        comboBox_PB_1_1->setCurrentIndex(26);
        comboBox_PB_3_1->setCurrentIndex(26);
        comboBox_PB_2_1->setCurrentIndex(26);
        comboBox_PB_1_2->setCurrentIndex(26);
        comboBox_PB_5_1->setCurrentIndex(26);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", nullptr));
        ComboBox_Set_R1->setItemText(0, QApplication::translate("MainWindow", "0", nullptr));
        ComboBox_Set_R1->setItemText(1, QApplication::translate("MainWindow", "1", nullptr));
        ComboBox_Set_R1->setItemText(2, QApplication::translate("MainWindow", "2", nullptr));
        ComboBox_Set_R1->setItemText(3, QApplication::translate("MainWindow", "3", nullptr));
        ComboBox_Set_R1->setItemText(4, QApplication::translate("MainWindow", "4", nullptr));
        ComboBox_Set_R1->setItemText(5, QApplication::translate("MainWindow", "5", nullptr));
        ComboBox_Set_R1->setItemText(6, QApplication::translate("MainWindow", "6", nullptr));
        ComboBox_Set_R1->setItemText(7, QApplication::translate("MainWindow", "7", nullptr));
        ComboBox_Set_R1->setItemText(8, QApplication::translate("MainWindow", "8", nullptr));
        ComboBox_Set_R1->setItemText(9, QApplication::translate("MainWindow", "9", nullptr));
        ComboBox_Set_R1->setItemText(10, QApplication::translate("MainWindow", "10", nullptr));
        ComboBox_Set_R1->setItemText(11, QApplication::translate("MainWindow", "11", nullptr));
        ComboBox_Set_R1->setItemText(12, QApplication::translate("MainWindow", "12", nullptr));
        ComboBox_Set_R1->setItemText(13, QApplication::translate("MainWindow", "13", nullptr));
        ComboBox_Set_R1->setItemText(14, QApplication::translate("MainWindow", "14", nullptr));
        ComboBox_Set_R1->setItemText(15, QApplication::translate("MainWindow", "15", nullptr));
        ComboBox_Set_R1->setItemText(16, QApplication::translate("MainWindow", "16", nullptr));
        ComboBox_Set_R1->setItemText(17, QApplication::translate("MainWindow", "17", nullptr));
        ComboBox_Set_R1->setItemText(18, QApplication::translate("MainWindow", "18", nullptr));
        ComboBox_Set_R1->setItemText(19, QApplication::translate("MainWindow", "19", nullptr));
        ComboBox_Set_R1->setItemText(20, QApplication::translate("MainWindow", "20", nullptr));
        ComboBox_Set_R1->setItemText(21, QApplication::translate("MainWindow", "21", nullptr));
        ComboBox_Set_R1->setItemText(22, QApplication::translate("MainWindow", "22", nullptr));
        ComboBox_Set_R1->setItemText(23, QApplication::translate("MainWindow", "23", nullptr));
        ComboBox_Set_R1->setItemText(24, QApplication::translate("MainWindow", "24", nullptr));
        ComboBox_Set_R1->setItemText(25, QApplication::translate("MainWindow", "25", nullptr));

        Label_Set_R1->setText(QApplication::translate("MainWindow", "Settaggio Rotore I", nullptr));
        Label_Start_R1->setText(QApplication::translate("MainWindow", "Lettera Iniziale Rotore I", nullptr));
        ComboBox_Start_R1->setItemText(0, QApplication::translate("MainWindow", "A", nullptr));
        ComboBox_Start_R1->setItemText(1, QApplication::translate("MainWindow", "B", nullptr));
        ComboBox_Start_R1->setItemText(2, QApplication::translate("MainWindow", "C", nullptr));
        ComboBox_Start_R1->setItemText(3, QApplication::translate("MainWindow", "D", nullptr));
        ComboBox_Start_R1->setItemText(4, QApplication::translate("MainWindow", "E", nullptr));
        ComboBox_Start_R1->setItemText(5, QApplication::translate("MainWindow", "F", nullptr));
        ComboBox_Start_R1->setItemText(6, QApplication::translate("MainWindow", "G", nullptr));
        ComboBox_Start_R1->setItemText(7, QApplication::translate("MainWindow", "H", nullptr));
        ComboBox_Start_R1->setItemText(8, QApplication::translate("MainWindow", "I", nullptr));
        ComboBox_Start_R1->setItemText(9, QApplication::translate("MainWindow", "J", nullptr));
        ComboBox_Start_R1->setItemText(10, QApplication::translate("MainWindow", "K", nullptr));
        ComboBox_Start_R1->setItemText(11, QApplication::translate("MainWindow", "L", nullptr));
        ComboBox_Start_R1->setItemText(12, QApplication::translate("MainWindow", "M", nullptr));
        ComboBox_Start_R1->setItemText(13, QApplication::translate("MainWindow", "N", nullptr));
        ComboBox_Start_R1->setItemText(14, QApplication::translate("MainWindow", "O", nullptr));
        ComboBox_Start_R1->setItemText(15, QApplication::translate("MainWindow", "P", nullptr));
        ComboBox_Start_R1->setItemText(16, QApplication::translate("MainWindow", "Q", nullptr));
        ComboBox_Start_R1->setItemText(17, QApplication::translate("MainWindow", "R", nullptr));
        ComboBox_Start_R1->setItemText(18, QApplication::translate("MainWindow", "S", nullptr));
        ComboBox_Start_R1->setItemText(19, QApplication::translate("MainWindow", "T", nullptr));
        ComboBox_Start_R1->setItemText(20, QApplication::translate("MainWindow", "U", nullptr));
        ComboBox_Start_R1->setItemText(21, QApplication::translate("MainWindow", "V", nullptr));
        ComboBox_Start_R1->setItemText(22, QApplication::translate("MainWindow", "W", nullptr));
        ComboBox_Start_R1->setItemText(23, QApplication::translate("MainWindow", "X", nullptr));
        ComboBox_Start_R1->setItemText(24, QApplication::translate("MainWindow", "Y", nullptr));
        ComboBox_Start_R1->setItemText(25, QApplication::translate("MainWindow", "Z", nullptr));

        PlugBoard->setTitle(QString());
        comboBox_PB_5_2->setItemText(0, QApplication::translate("MainWindow", "A", nullptr));
        comboBox_PB_5_2->setItemText(1, QApplication::translate("MainWindow", "B", nullptr));
        comboBox_PB_5_2->setItemText(2, QApplication::translate("MainWindow", "C", nullptr));
        comboBox_PB_5_2->setItemText(3, QApplication::translate("MainWindow", "D", nullptr));
        comboBox_PB_5_2->setItemText(4, QApplication::translate("MainWindow", "E", nullptr));
        comboBox_PB_5_2->setItemText(5, QApplication::translate("MainWindow", "F", nullptr));
        comboBox_PB_5_2->setItemText(6, QApplication::translate("MainWindow", "G", nullptr));
        comboBox_PB_5_2->setItemText(7, QApplication::translate("MainWindow", "H", nullptr));
        comboBox_PB_5_2->setItemText(8, QApplication::translate("MainWindow", "I", nullptr));
        comboBox_PB_5_2->setItemText(9, QApplication::translate("MainWindow", "J", nullptr));
        comboBox_PB_5_2->setItemText(10, QApplication::translate("MainWindow", "K", nullptr));
        comboBox_PB_5_2->setItemText(11, QApplication::translate("MainWindow", "L", nullptr));
        comboBox_PB_5_2->setItemText(12, QApplication::translate("MainWindow", "M", nullptr));
        comboBox_PB_5_2->setItemText(13, QApplication::translate("MainWindow", "N", nullptr));
        comboBox_PB_5_2->setItemText(14, QApplication::translate("MainWindow", "O", nullptr));
        comboBox_PB_5_2->setItemText(15, QApplication::translate("MainWindow", "P", nullptr));
        comboBox_PB_5_2->setItemText(16, QApplication::translate("MainWindow", "Q", nullptr));
        comboBox_PB_5_2->setItemText(17, QApplication::translate("MainWindow", "R", nullptr));
        comboBox_PB_5_2->setItemText(18, QApplication::translate("MainWindow", "S", nullptr));
        comboBox_PB_5_2->setItemText(19, QApplication::translate("MainWindow", "T", nullptr));
        comboBox_PB_5_2->setItemText(20, QApplication::translate("MainWindow", "U", nullptr));
        comboBox_PB_5_2->setItemText(21, QApplication::translate("MainWindow", "V", nullptr));
        comboBox_PB_5_2->setItemText(22, QApplication::translate("MainWindow", "W", nullptr));
        comboBox_PB_5_2->setItemText(23, QApplication::translate("MainWindow", "X", nullptr));
        comboBox_PB_5_2->setItemText(24, QApplication::translate("MainWindow", "Y", nullptr));
        comboBox_PB_5_2->setItemText(25, QApplication::translate("MainWindow", "Z", nullptr));
        comboBox_PB_5_2->setItemText(26, QApplication::translate("MainWindow", "-", nullptr));

        comboBox_PB_4_2->setItemText(0, QApplication::translate("MainWindow", "A", nullptr));
        comboBox_PB_4_2->setItemText(1, QApplication::translate("MainWindow", "B", nullptr));
        comboBox_PB_4_2->setItemText(2, QApplication::translate("MainWindow", "C", nullptr));
        comboBox_PB_4_2->setItemText(3, QApplication::translate("MainWindow", "D", nullptr));
        comboBox_PB_4_2->setItemText(4, QApplication::translate("MainWindow", "E", nullptr));
        comboBox_PB_4_2->setItemText(5, QApplication::translate("MainWindow", "F", nullptr));
        comboBox_PB_4_2->setItemText(6, QApplication::translate("MainWindow", "G", nullptr));
        comboBox_PB_4_2->setItemText(7, QApplication::translate("MainWindow", "H", nullptr));
        comboBox_PB_4_2->setItemText(8, QApplication::translate("MainWindow", "I", nullptr));
        comboBox_PB_4_2->setItemText(9, QApplication::translate("MainWindow", "J", nullptr));
        comboBox_PB_4_2->setItemText(10, QApplication::translate("MainWindow", "K", nullptr));
        comboBox_PB_4_2->setItemText(11, QApplication::translate("MainWindow", "L", nullptr));
        comboBox_PB_4_2->setItemText(12, QApplication::translate("MainWindow", "M", nullptr));
        comboBox_PB_4_2->setItemText(13, QApplication::translate("MainWindow", "N", nullptr));
        comboBox_PB_4_2->setItemText(14, QApplication::translate("MainWindow", "O", nullptr));
        comboBox_PB_4_2->setItemText(15, QApplication::translate("MainWindow", "P", nullptr));
        comboBox_PB_4_2->setItemText(16, QApplication::translate("MainWindow", "Q", nullptr));
        comboBox_PB_4_2->setItemText(17, QApplication::translate("MainWindow", "R", nullptr));
        comboBox_PB_4_2->setItemText(18, QApplication::translate("MainWindow", "S", nullptr));
        comboBox_PB_4_2->setItemText(19, QApplication::translate("MainWindow", "T", nullptr));
        comboBox_PB_4_2->setItemText(20, QApplication::translate("MainWindow", "U", nullptr));
        comboBox_PB_4_2->setItemText(21, QApplication::translate("MainWindow", "V", nullptr));
        comboBox_PB_4_2->setItemText(22, QApplication::translate("MainWindow", "W", nullptr));
        comboBox_PB_4_2->setItemText(23, QApplication::translate("MainWindow", "X", nullptr));
        comboBox_PB_4_2->setItemText(24, QApplication::translate("MainWindow", "Y", nullptr));
        comboBox_PB_4_2->setItemText(25, QApplication::translate("MainWindow", "Z", nullptr));
        comboBox_PB_4_2->setItemText(26, QApplication::translate("MainWindow", "-", nullptr));

        comboBox_PB_3_2->setItemText(0, QApplication::translate("MainWindow", "A", nullptr));
        comboBox_PB_3_2->setItemText(1, QApplication::translate("MainWindow", "B", nullptr));
        comboBox_PB_3_2->setItemText(2, QApplication::translate("MainWindow", "C", nullptr));
        comboBox_PB_3_2->setItemText(3, QApplication::translate("MainWindow", "D", nullptr));
        comboBox_PB_3_2->setItemText(4, QApplication::translate("MainWindow", "E", nullptr));
        comboBox_PB_3_2->setItemText(5, QApplication::translate("MainWindow", "F", nullptr));
        comboBox_PB_3_2->setItemText(6, QApplication::translate("MainWindow", "G", nullptr));
        comboBox_PB_3_2->setItemText(7, QApplication::translate("MainWindow", "H", nullptr));
        comboBox_PB_3_2->setItemText(8, QApplication::translate("MainWindow", "I", nullptr));
        comboBox_PB_3_2->setItemText(9, QApplication::translate("MainWindow", "J", nullptr));
        comboBox_PB_3_2->setItemText(10, QApplication::translate("MainWindow", "K", nullptr));
        comboBox_PB_3_2->setItemText(11, QApplication::translate("MainWindow", "L", nullptr));
        comboBox_PB_3_2->setItemText(12, QApplication::translate("MainWindow", "M", nullptr));
        comboBox_PB_3_2->setItemText(13, QApplication::translate("MainWindow", "N", nullptr));
        comboBox_PB_3_2->setItemText(14, QApplication::translate("MainWindow", "O", nullptr));
        comboBox_PB_3_2->setItemText(15, QApplication::translate("MainWindow", "P", nullptr));
        comboBox_PB_3_2->setItemText(16, QApplication::translate("MainWindow", "Q", nullptr));
        comboBox_PB_3_2->setItemText(17, QApplication::translate("MainWindow", "R", nullptr));
        comboBox_PB_3_2->setItemText(18, QApplication::translate("MainWindow", "S", nullptr));
        comboBox_PB_3_2->setItemText(19, QApplication::translate("MainWindow", "T", nullptr));
        comboBox_PB_3_2->setItemText(20, QApplication::translate("MainWindow", "U", nullptr));
        comboBox_PB_3_2->setItemText(21, QApplication::translate("MainWindow", "V", nullptr));
        comboBox_PB_3_2->setItemText(22, QApplication::translate("MainWindow", "W", nullptr));
        comboBox_PB_3_2->setItemText(23, QApplication::translate("MainWindow", "X", nullptr));
        comboBox_PB_3_2->setItemText(24, QApplication::translate("MainWindow", "Y", nullptr));
        comboBox_PB_3_2->setItemText(25, QApplication::translate("MainWindow", "Z", nullptr));
        comboBox_PB_3_2->setItemText(26, QApplication::translate("MainWindow", "-", nullptr));

        comboBox_PB_2_2->setItemText(0, QApplication::translate("MainWindow", "A", nullptr));
        comboBox_PB_2_2->setItemText(1, QApplication::translate("MainWindow", "B", nullptr));
        comboBox_PB_2_2->setItemText(2, QApplication::translate("MainWindow", "C", nullptr));
        comboBox_PB_2_2->setItemText(3, QApplication::translate("MainWindow", "D", nullptr));
        comboBox_PB_2_2->setItemText(4, QApplication::translate("MainWindow", "E", nullptr));
        comboBox_PB_2_2->setItemText(5, QApplication::translate("MainWindow", "F", nullptr));
        comboBox_PB_2_2->setItemText(6, QApplication::translate("MainWindow", "G", nullptr));
        comboBox_PB_2_2->setItemText(7, QApplication::translate("MainWindow", "H", nullptr));
        comboBox_PB_2_2->setItemText(8, QApplication::translate("MainWindow", "I", nullptr));
        comboBox_PB_2_2->setItemText(9, QApplication::translate("MainWindow", "J", nullptr));
        comboBox_PB_2_2->setItemText(10, QApplication::translate("MainWindow", "K", nullptr));
        comboBox_PB_2_2->setItemText(11, QApplication::translate("MainWindow", "L", nullptr));
        comboBox_PB_2_2->setItemText(12, QApplication::translate("MainWindow", "M", nullptr));
        comboBox_PB_2_2->setItemText(13, QApplication::translate("MainWindow", "N", nullptr));
        comboBox_PB_2_2->setItemText(14, QApplication::translate("MainWindow", "O", nullptr));
        comboBox_PB_2_2->setItemText(15, QApplication::translate("MainWindow", "P", nullptr));
        comboBox_PB_2_2->setItemText(16, QApplication::translate("MainWindow", "Q", nullptr));
        comboBox_PB_2_2->setItemText(17, QApplication::translate("MainWindow", "R", nullptr));
        comboBox_PB_2_2->setItemText(18, QApplication::translate("MainWindow", "S", nullptr));
        comboBox_PB_2_2->setItemText(19, QApplication::translate("MainWindow", "T", nullptr));
        comboBox_PB_2_2->setItemText(20, QApplication::translate("MainWindow", "U", nullptr));
        comboBox_PB_2_2->setItemText(21, QApplication::translate("MainWindow", "V", nullptr));
        comboBox_PB_2_2->setItemText(22, QApplication::translate("MainWindow", "W", nullptr));
        comboBox_PB_2_2->setItemText(23, QApplication::translate("MainWindow", "X", nullptr));
        comboBox_PB_2_2->setItemText(24, QApplication::translate("MainWindow", "Y", nullptr));
        comboBox_PB_2_2->setItemText(25, QApplication::translate("MainWindow", "Z", nullptr));
        comboBox_PB_2_2->setItemText(26, QApplication::translate("MainWindow", "-", nullptr));

        comboBox_PB_4_1->setItemText(0, QApplication::translate("MainWindow", "A", nullptr));
        comboBox_PB_4_1->setItemText(1, QApplication::translate("MainWindow", "B", nullptr));
        comboBox_PB_4_1->setItemText(2, QApplication::translate("MainWindow", "C", nullptr));
        comboBox_PB_4_1->setItemText(3, QApplication::translate("MainWindow", "D", nullptr));
        comboBox_PB_4_1->setItemText(4, QApplication::translate("MainWindow", "E", nullptr));
        comboBox_PB_4_1->setItemText(5, QApplication::translate("MainWindow", "F", nullptr));
        comboBox_PB_4_1->setItemText(6, QApplication::translate("MainWindow", "G", nullptr));
        comboBox_PB_4_1->setItemText(7, QApplication::translate("MainWindow", "H", nullptr));
        comboBox_PB_4_1->setItemText(8, QApplication::translate("MainWindow", "I", nullptr));
        comboBox_PB_4_1->setItemText(9, QApplication::translate("MainWindow", "J", nullptr));
        comboBox_PB_4_1->setItemText(10, QApplication::translate("MainWindow", "K", nullptr));
        comboBox_PB_4_1->setItemText(11, QApplication::translate("MainWindow", "L", nullptr));
        comboBox_PB_4_1->setItemText(12, QApplication::translate("MainWindow", "M", nullptr));
        comboBox_PB_4_1->setItemText(13, QApplication::translate("MainWindow", "N", nullptr));
        comboBox_PB_4_1->setItemText(14, QApplication::translate("MainWindow", "O", nullptr));
        comboBox_PB_4_1->setItemText(15, QApplication::translate("MainWindow", "P", nullptr));
        comboBox_PB_4_1->setItemText(16, QApplication::translate("MainWindow", "Q", nullptr));
        comboBox_PB_4_1->setItemText(17, QApplication::translate("MainWindow", "R", nullptr));
        comboBox_PB_4_1->setItemText(18, QApplication::translate("MainWindow", "S", nullptr));
        comboBox_PB_4_1->setItemText(19, QApplication::translate("MainWindow", "T", nullptr));
        comboBox_PB_4_1->setItemText(20, QApplication::translate("MainWindow", "U", nullptr));
        comboBox_PB_4_1->setItemText(21, QApplication::translate("MainWindow", "V", nullptr));
        comboBox_PB_4_1->setItemText(22, QApplication::translate("MainWindow", "W", nullptr));
        comboBox_PB_4_1->setItemText(23, QApplication::translate("MainWindow", "X", nullptr));
        comboBox_PB_4_1->setItemText(24, QApplication::translate("MainWindow", "Y", nullptr));
        comboBox_PB_4_1->setItemText(25, QApplication::translate("MainWindow", "Z", nullptr));
        comboBox_PB_4_1->setItemText(26, QApplication::translate("MainWindow", "-", nullptr));

        comboBox_PB_1_1->setItemText(0, QApplication::translate("MainWindow", "A", nullptr));
        comboBox_PB_1_1->setItemText(1, QApplication::translate("MainWindow", "B", nullptr));
        comboBox_PB_1_1->setItemText(2, QApplication::translate("MainWindow", "C", nullptr));
        comboBox_PB_1_1->setItemText(3, QApplication::translate("MainWindow", "D", nullptr));
        comboBox_PB_1_1->setItemText(4, QApplication::translate("MainWindow", "E", nullptr));
        comboBox_PB_1_1->setItemText(5, QApplication::translate("MainWindow", "F", nullptr));
        comboBox_PB_1_1->setItemText(6, QApplication::translate("MainWindow", "G", nullptr));
        comboBox_PB_1_1->setItemText(7, QApplication::translate("MainWindow", "H", nullptr));
        comboBox_PB_1_1->setItemText(8, QApplication::translate("MainWindow", "I", nullptr));
        comboBox_PB_1_1->setItemText(9, QApplication::translate("MainWindow", "J", nullptr));
        comboBox_PB_1_1->setItemText(10, QApplication::translate("MainWindow", "K", nullptr));
        comboBox_PB_1_1->setItemText(11, QApplication::translate("MainWindow", "L", nullptr));
        comboBox_PB_1_1->setItemText(12, QApplication::translate("MainWindow", "M", nullptr));
        comboBox_PB_1_1->setItemText(13, QApplication::translate("MainWindow", "N", nullptr));
        comboBox_PB_1_1->setItemText(14, QApplication::translate("MainWindow", "O", nullptr));
        comboBox_PB_1_1->setItemText(15, QApplication::translate("MainWindow", "P", nullptr));
        comboBox_PB_1_1->setItemText(16, QApplication::translate("MainWindow", "Q", nullptr));
        comboBox_PB_1_1->setItemText(17, QApplication::translate("MainWindow", "R", nullptr));
        comboBox_PB_1_1->setItemText(18, QApplication::translate("MainWindow", "S", nullptr));
        comboBox_PB_1_1->setItemText(19, QApplication::translate("MainWindow", "T", nullptr));
        comboBox_PB_1_1->setItemText(20, QApplication::translate("MainWindow", "U", nullptr));
        comboBox_PB_1_1->setItemText(21, QApplication::translate("MainWindow", "V", nullptr));
        comboBox_PB_1_1->setItemText(22, QApplication::translate("MainWindow", "W", nullptr));
        comboBox_PB_1_1->setItemText(23, QApplication::translate("MainWindow", "X", nullptr));
        comboBox_PB_1_1->setItemText(24, QApplication::translate("MainWindow", "Y", nullptr));
        comboBox_PB_1_1->setItemText(25, QApplication::translate("MainWindow", "Z", nullptr));
        comboBox_PB_1_1->setItemText(26, QApplication::translate("MainWindow", "-", nullptr));

        comboBox_PB_3_1->setItemText(0, QApplication::translate("MainWindow", "A", nullptr));
        comboBox_PB_3_1->setItemText(1, QApplication::translate("MainWindow", "B", nullptr));
        comboBox_PB_3_1->setItemText(2, QApplication::translate("MainWindow", "C", nullptr));
        comboBox_PB_3_1->setItemText(3, QApplication::translate("MainWindow", "D", nullptr));
        comboBox_PB_3_1->setItemText(4, QApplication::translate("MainWindow", "E", nullptr));
        comboBox_PB_3_1->setItemText(5, QApplication::translate("MainWindow", "F", nullptr));
        comboBox_PB_3_1->setItemText(6, QApplication::translate("MainWindow", "G", nullptr));
        comboBox_PB_3_1->setItemText(7, QApplication::translate("MainWindow", "H", nullptr));
        comboBox_PB_3_1->setItemText(8, QApplication::translate("MainWindow", "I", nullptr));
        comboBox_PB_3_1->setItemText(9, QApplication::translate("MainWindow", "J", nullptr));
        comboBox_PB_3_1->setItemText(10, QApplication::translate("MainWindow", "K", nullptr));
        comboBox_PB_3_1->setItemText(11, QApplication::translate("MainWindow", "L", nullptr));
        comboBox_PB_3_1->setItemText(12, QApplication::translate("MainWindow", "M", nullptr));
        comboBox_PB_3_1->setItemText(13, QApplication::translate("MainWindow", "N", nullptr));
        comboBox_PB_3_1->setItemText(14, QApplication::translate("MainWindow", "O", nullptr));
        comboBox_PB_3_1->setItemText(15, QApplication::translate("MainWindow", "P", nullptr));
        comboBox_PB_3_1->setItemText(16, QApplication::translate("MainWindow", "Q", nullptr));
        comboBox_PB_3_1->setItemText(17, QApplication::translate("MainWindow", "R", nullptr));
        comboBox_PB_3_1->setItemText(18, QApplication::translate("MainWindow", "S", nullptr));
        comboBox_PB_3_1->setItemText(19, QApplication::translate("MainWindow", "T", nullptr));
        comboBox_PB_3_1->setItemText(20, QApplication::translate("MainWindow", "U", nullptr));
        comboBox_PB_3_1->setItemText(21, QApplication::translate("MainWindow", "V", nullptr));
        comboBox_PB_3_1->setItemText(22, QApplication::translate("MainWindow", "W", nullptr));
        comboBox_PB_3_1->setItemText(23, QApplication::translate("MainWindow", "X", nullptr));
        comboBox_PB_3_1->setItemText(24, QApplication::translate("MainWindow", "Y", nullptr));
        comboBox_PB_3_1->setItemText(25, QApplication::translate("MainWindow", "Z", nullptr));
        comboBox_PB_3_1->setItemText(26, QApplication::translate("MainWindow", "-", nullptr));

        comboBox_PB_2_1->setItemText(0, QApplication::translate("MainWindow", "A", nullptr));
        comboBox_PB_2_1->setItemText(1, QApplication::translate("MainWindow", "B", nullptr));
        comboBox_PB_2_1->setItemText(2, QApplication::translate("MainWindow", "C", nullptr));
        comboBox_PB_2_1->setItemText(3, QApplication::translate("MainWindow", "D", nullptr));
        comboBox_PB_2_1->setItemText(4, QApplication::translate("MainWindow", "E", nullptr));
        comboBox_PB_2_1->setItemText(5, QApplication::translate("MainWindow", "F", nullptr));
        comboBox_PB_2_1->setItemText(6, QApplication::translate("MainWindow", "G", nullptr));
        comboBox_PB_2_1->setItemText(7, QApplication::translate("MainWindow", "H", nullptr));
        comboBox_PB_2_1->setItemText(8, QApplication::translate("MainWindow", "I", nullptr));
        comboBox_PB_2_1->setItemText(9, QApplication::translate("MainWindow", "J", nullptr));
        comboBox_PB_2_1->setItemText(10, QApplication::translate("MainWindow", "K", nullptr));
        comboBox_PB_2_1->setItemText(11, QApplication::translate("MainWindow", "L", nullptr));
        comboBox_PB_2_1->setItemText(12, QApplication::translate("MainWindow", "M", nullptr));
        comboBox_PB_2_1->setItemText(13, QApplication::translate("MainWindow", "N", nullptr));
        comboBox_PB_2_1->setItemText(14, QApplication::translate("MainWindow", "O", nullptr));
        comboBox_PB_2_1->setItemText(15, QApplication::translate("MainWindow", "P", nullptr));
        comboBox_PB_2_1->setItemText(16, QApplication::translate("MainWindow", "Q", nullptr));
        comboBox_PB_2_1->setItemText(17, QApplication::translate("MainWindow", "R", nullptr));
        comboBox_PB_2_1->setItemText(18, QApplication::translate("MainWindow", "S", nullptr));
        comboBox_PB_2_1->setItemText(19, QApplication::translate("MainWindow", "T", nullptr));
        comboBox_PB_2_1->setItemText(20, QApplication::translate("MainWindow", "U", nullptr));
        comboBox_PB_2_1->setItemText(21, QApplication::translate("MainWindow", "V", nullptr));
        comboBox_PB_2_1->setItemText(22, QApplication::translate("MainWindow", "W", nullptr));
        comboBox_PB_2_1->setItemText(23, QApplication::translate("MainWindow", "X", nullptr));
        comboBox_PB_2_1->setItemText(24, QApplication::translate("MainWindow", "Y", nullptr));
        comboBox_PB_2_1->setItemText(25, QApplication::translate("MainWindow", "Z", nullptr));
        comboBox_PB_2_1->setItemText(26, QApplication::translate("MainWindow", "-", nullptr));

        comboBox_PB_1_2->setItemText(0, QApplication::translate("MainWindow", "A", nullptr));
        comboBox_PB_1_2->setItemText(1, QApplication::translate("MainWindow", "B", nullptr));
        comboBox_PB_1_2->setItemText(2, QApplication::translate("MainWindow", "C", nullptr));
        comboBox_PB_1_2->setItemText(3, QApplication::translate("MainWindow", "D", nullptr));
        comboBox_PB_1_2->setItemText(4, QApplication::translate("MainWindow", "E", nullptr));
        comboBox_PB_1_2->setItemText(5, QApplication::translate("MainWindow", "F", nullptr));
        comboBox_PB_1_2->setItemText(6, QApplication::translate("MainWindow", "G", nullptr));
        comboBox_PB_1_2->setItemText(7, QApplication::translate("MainWindow", "H", nullptr));
        comboBox_PB_1_2->setItemText(8, QApplication::translate("MainWindow", "I", nullptr));
        comboBox_PB_1_2->setItemText(9, QApplication::translate("MainWindow", "J", nullptr));
        comboBox_PB_1_2->setItemText(10, QApplication::translate("MainWindow", "K", nullptr));
        comboBox_PB_1_2->setItemText(11, QApplication::translate("MainWindow", "L", nullptr));
        comboBox_PB_1_2->setItemText(12, QApplication::translate("MainWindow", "M", nullptr));
        comboBox_PB_1_2->setItemText(13, QApplication::translate("MainWindow", "N", nullptr));
        comboBox_PB_1_2->setItemText(14, QApplication::translate("MainWindow", "O", nullptr));
        comboBox_PB_1_2->setItemText(15, QApplication::translate("MainWindow", "P", nullptr));
        comboBox_PB_1_2->setItemText(16, QApplication::translate("MainWindow", "Q", nullptr));
        comboBox_PB_1_2->setItemText(17, QApplication::translate("MainWindow", "R", nullptr));
        comboBox_PB_1_2->setItemText(18, QApplication::translate("MainWindow", "S", nullptr));
        comboBox_PB_1_2->setItemText(19, QApplication::translate("MainWindow", "T", nullptr));
        comboBox_PB_1_2->setItemText(20, QApplication::translate("MainWindow", "U", nullptr));
        comboBox_PB_1_2->setItemText(21, QApplication::translate("MainWindow", "V", nullptr));
        comboBox_PB_1_2->setItemText(22, QApplication::translate("MainWindow", "W", nullptr));
        comboBox_PB_1_2->setItemText(23, QApplication::translate("MainWindow", "X", nullptr));
        comboBox_PB_1_2->setItemText(24, QApplication::translate("MainWindow", "Y", nullptr));
        comboBox_PB_1_2->setItemText(25, QApplication::translate("MainWindow", "Z", nullptr));
        comboBox_PB_1_2->setItemText(26, QApplication::translate("MainWindow", "-", nullptr));

        comboBox_PB_5_1->setItemText(0, QApplication::translate("MainWindow", "A", nullptr));
        comboBox_PB_5_1->setItemText(1, QApplication::translate("MainWindow", "B", nullptr));
        comboBox_PB_5_1->setItemText(2, QApplication::translate("MainWindow", "C", nullptr));
        comboBox_PB_5_1->setItemText(3, QApplication::translate("MainWindow", "D", nullptr));
        comboBox_PB_5_1->setItemText(4, QApplication::translate("MainWindow", "E", nullptr));
        comboBox_PB_5_1->setItemText(5, QApplication::translate("MainWindow", "F", nullptr));
        comboBox_PB_5_1->setItemText(6, QApplication::translate("MainWindow", "G", nullptr));
        comboBox_PB_5_1->setItemText(7, QApplication::translate("MainWindow", "H", nullptr));
        comboBox_PB_5_1->setItemText(8, QApplication::translate("MainWindow", "I", nullptr));
        comboBox_PB_5_1->setItemText(9, QApplication::translate("MainWindow", "J", nullptr));
        comboBox_PB_5_1->setItemText(10, QApplication::translate("MainWindow", "K", nullptr));
        comboBox_PB_5_1->setItemText(11, QApplication::translate("MainWindow", "L", nullptr));
        comboBox_PB_5_1->setItemText(12, QApplication::translate("MainWindow", "M", nullptr));
        comboBox_PB_5_1->setItemText(13, QApplication::translate("MainWindow", "N", nullptr));
        comboBox_PB_5_1->setItemText(14, QApplication::translate("MainWindow", "O", nullptr));
        comboBox_PB_5_1->setItemText(15, QApplication::translate("MainWindow", "P", nullptr));
        comboBox_PB_5_1->setItemText(16, QApplication::translate("MainWindow", "Q", nullptr));
        comboBox_PB_5_1->setItemText(17, QApplication::translate("MainWindow", "R", nullptr));
        comboBox_PB_5_1->setItemText(18, QApplication::translate("MainWindow", "S", nullptr));
        comboBox_PB_5_1->setItemText(19, QApplication::translate("MainWindow", "T", nullptr));
        comboBox_PB_5_1->setItemText(20, QApplication::translate("MainWindow", "U", nullptr));
        comboBox_PB_5_1->setItemText(21, QApplication::translate("MainWindow", "V", nullptr));
        comboBox_PB_5_1->setItemText(22, QApplication::translate("MainWindow", "W", nullptr));
        comboBox_PB_5_1->setItemText(23, QApplication::translate("MainWindow", "X", nullptr));
        comboBox_PB_5_1->setItemText(24, QApplication::translate("MainWindow", "Y", nullptr));
        comboBox_PB_5_1->setItemText(25, QApplication::translate("MainWindow", "Z", nullptr));
        comboBox_PB_5_1->setItemText(26, QApplication::translate("MainWindow", "-", nullptr));

        label_3->setText(QString());
        label_Nome->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">CANALI DAVIDE    5</span><span style=\" font-weight:600; vertical-align:super;\">a</span><span style=\" font-weight:600;\">CL</span></p><p><span style=\" font-weight:600;\">ISISS VALLE SERIANA</span></p></body></html>", nullptr));
        label_Logo->setText(QString());
        label_8->setText(QString());
        label_9->setText(QString());
        label_10->setText(QString());
        label_11->setText(QString());
        groupBox->setTitle(QString());
        Btn_A->setText(QApplication::translate("MainWindow", "A", nullptr));
        Btn_O->setText(QApplication::translate("MainWindow", "O", nullptr));
        Btn_I->setText(QApplication::translate("MainWindow", "I", nullptr));
        Btn_U->setText(QApplication::translate("MainWindow", "U", nullptr));
        Btn_Z->setText(QApplication::translate("MainWindow", "Z", nullptr));
        Btn_T->setText(QApplication::translate("MainWindow", "T", nullptr));
        Btn_R->setText(QApplication::translate("MainWindow", "R", nullptr));
        Btn_E->setText(QApplication::translate("MainWindow", "E", nullptr));
        Btn_W->setText(QApplication::translate("MainWindow", "W", nullptr));
        Btn_Q->setText(QApplication::translate("MainWindow", "Q", nullptr));
        Btn_S->setText(QApplication::translate("MainWindow", "S", nullptr));
        Btn_D->setText(QApplication::translate("MainWindow", "D", nullptr));
        Btn_F->setText(QApplication::translate("MainWindow", "F", nullptr));
        Btn_G->setText(QApplication::translate("MainWindow", "G", nullptr));
        Btn_H->setText(QApplication::translate("MainWindow", "H", nullptr));
        Btn_J->setText(QApplication::translate("MainWindow", "J", nullptr));
        Btn_K->setText(QApplication::translate("MainWindow", "K", nullptr));
        Btn_P->setText(QApplication::translate("MainWindow", "P", nullptr));
        Btn_Y->setText(QApplication::translate("MainWindow", "Y", nullptr));
        Btn_X->setText(QApplication::translate("MainWindow", "X", nullptr));
        Btn_C->setText(QApplication::translate("MainWindow", "C", nullptr));
        Btn_V->setText(QApplication::translate("MainWindow", "V", nullptr));
        Btn_B->setText(QApplication::translate("MainWindow", "B", nullptr));
        Btn_N->setText(QApplication::translate("MainWindow", "N", nullptr));
        Btn_M->setText(QApplication::translate("MainWindow", "M", nullptr));
        Btn_L->setText(QApplication::translate("MainWindow", "L", nullptr));
        ComboBox_Set_R2->setItemText(0, QApplication::translate("MainWindow", "0", nullptr));
        ComboBox_Set_R2->setItemText(1, QApplication::translate("MainWindow", "1", nullptr));
        ComboBox_Set_R2->setItemText(2, QApplication::translate("MainWindow", "2", nullptr));
        ComboBox_Set_R2->setItemText(3, QApplication::translate("MainWindow", "3", nullptr));
        ComboBox_Set_R2->setItemText(4, QApplication::translate("MainWindow", "4", nullptr));
        ComboBox_Set_R2->setItemText(5, QApplication::translate("MainWindow", "5", nullptr));
        ComboBox_Set_R2->setItemText(6, QApplication::translate("MainWindow", "6", nullptr));
        ComboBox_Set_R2->setItemText(7, QApplication::translate("MainWindow", "7", nullptr));
        ComboBox_Set_R2->setItemText(8, QApplication::translate("MainWindow", "8", nullptr));
        ComboBox_Set_R2->setItemText(9, QApplication::translate("MainWindow", "9", nullptr));
        ComboBox_Set_R2->setItemText(10, QApplication::translate("MainWindow", "10", nullptr));
        ComboBox_Set_R2->setItemText(11, QApplication::translate("MainWindow", "11", nullptr));
        ComboBox_Set_R2->setItemText(12, QApplication::translate("MainWindow", "12", nullptr));
        ComboBox_Set_R2->setItemText(13, QApplication::translate("MainWindow", "13", nullptr));
        ComboBox_Set_R2->setItemText(14, QApplication::translate("MainWindow", "14", nullptr));
        ComboBox_Set_R2->setItemText(15, QApplication::translate("MainWindow", "15", nullptr));
        ComboBox_Set_R2->setItemText(16, QApplication::translate("MainWindow", "16", nullptr));
        ComboBox_Set_R2->setItemText(17, QApplication::translate("MainWindow", "17", nullptr));
        ComboBox_Set_R2->setItemText(18, QApplication::translate("MainWindow", "18", nullptr));
        ComboBox_Set_R2->setItemText(19, QApplication::translate("MainWindow", "19", nullptr));
        ComboBox_Set_R2->setItemText(20, QApplication::translate("MainWindow", "20", nullptr));
        ComboBox_Set_R2->setItemText(21, QApplication::translate("MainWindow", "21", nullptr));
        ComboBox_Set_R2->setItemText(22, QApplication::translate("MainWindow", "22", nullptr));
        ComboBox_Set_R2->setItemText(23, QApplication::translate("MainWindow", "23", nullptr));
        ComboBox_Set_R2->setItemText(24, QApplication::translate("MainWindow", "24", nullptr));
        ComboBox_Set_R2->setItemText(25, QApplication::translate("MainWindow", "25", nullptr));

        ComboBox_Start_R2->setItemText(0, QApplication::translate("MainWindow", "A", nullptr));
        ComboBox_Start_R2->setItemText(1, QApplication::translate("MainWindow", "B", nullptr));
        ComboBox_Start_R2->setItemText(2, QApplication::translate("MainWindow", "C", nullptr));
        ComboBox_Start_R2->setItemText(3, QApplication::translate("MainWindow", "D", nullptr));
        ComboBox_Start_R2->setItemText(4, QApplication::translate("MainWindow", "E", nullptr));
        ComboBox_Start_R2->setItemText(5, QApplication::translate("MainWindow", "F", nullptr));
        ComboBox_Start_R2->setItemText(6, QApplication::translate("MainWindow", "G", nullptr));
        ComboBox_Start_R2->setItemText(7, QApplication::translate("MainWindow", "H", nullptr));
        ComboBox_Start_R2->setItemText(8, QApplication::translate("MainWindow", "I", nullptr));
        ComboBox_Start_R2->setItemText(9, QApplication::translate("MainWindow", "J", nullptr));
        ComboBox_Start_R2->setItemText(10, QApplication::translate("MainWindow", "K", nullptr));
        ComboBox_Start_R2->setItemText(11, QApplication::translate("MainWindow", "L", nullptr));
        ComboBox_Start_R2->setItemText(12, QApplication::translate("MainWindow", "M", nullptr));
        ComboBox_Start_R2->setItemText(13, QApplication::translate("MainWindow", "N", nullptr));
        ComboBox_Start_R2->setItemText(14, QApplication::translate("MainWindow", "O", nullptr));
        ComboBox_Start_R2->setItemText(15, QApplication::translate("MainWindow", "P", nullptr));
        ComboBox_Start_R2->setItemText(16, QApplication::translate("MainWindow", "Q", nullptr));
        ComboBox_Start_R2->setItemText(17, QApplication::translate("MainWindow", "R", nullptr));
        ComboBox_Start_R2->setItemText(18, QApplication::translate("MainWindow", "S", nullptr));
        ComboBox_Start_R2->setItemText(19, QApplication::translate("MainWindow", "T", nullptr));
        ComboBox_Start_R2->setItemText(20, QApplication::translate("MainWindow", "U", nullptr));
        ComboBox_Start_R2->setItemText(21, QApplication::translate("MainWindow", "V", nullptr));
        ComboBox_Start_R2->setItemText(22, QApplication::translate("MainWindow", "W", nullptr));
        ComboBox_Start_R2->setItemText(23, QApplication::translate("MainWindow", "X", nullptr));
        ComboBox_Start_R2->setItemText(24, QApplication::translate("MainWindow", "Y", nullptr));
        ComboBox_Start_R2->setItemText(25, QApplication::translate("MainWindow", "Z", nullptr));

        Label_Set_R2->setText(QApplication::translate("MainWindow", "Settaggio Rotore II", nullptr));
        Label_Start_R2->setText(QApplication::translate("MainWindow", "Lettera Iniziale Rotore II", nullptr));
        Label_Start_R3->setText(QApplication::translate("MainWindow", "Lettera Iniziale Rotore III", nullptr));
        ComboBox_Set_R3->setItemText(0, QApplication::translate("MainWindow", "0", nullptr));
        ComboBox_Set_R3->setItemText(1, QApplication::translate("MainWindow", "1", nullptr));
        ComboBox_Set_R3->setItemText(2, QApplication::translate("MainWindow", "2", nullptr));
        ComboBox_Set_R3->setItemText(3, QApplication::translate("MainWindow", "3", nullptr));
        ComboBox_Set_R3->setItemText(4, QApplication::translate("MainWindow", "4", nullptr));
        ComboBox_Set_R3->setItemText(5, QApplication::translate("MainWindow", "5", nullptr));
        ComboBox_Set_R3->setItemText(6, QApplication::translate("MainWindow", "6", nullptr));
        ComboBox_Set_R3->setItemText(7, QApplication::translate("MainWindow", "7", nullptr));
        ComboBox_Set_R3->setItemText(8, QApplication::translate("MainWindow", "8", nullptr));
        ComboBox_Set_R3->setItemText(9, QApplication::translate("MainWindow", "9", nullptr));
        ComboBox_Set_R3->setItemText(10, QApplication::translate("MainWindow", "10", nullptr));
        ComboBox_Set_R3->setItemText(11, QApplication::translate("MainWindow", "11", nullptr));
        ComboBox_Set_R3->setItemText(12, QApplication::translate("MainWindow", "12", nullptr));
        ComboBox_Set_R3->setItemText(13, QApplication::translate("MainWindow", "13", nullptr));
        ComboBox_Set_R3->setItemText(14, QApplication::translate("MainWindow", "14", nullptr));
        ComboBox_Set_R3->setItemText(15, QApplication::translate("MainWindow", "15", nullptr));
        ComboBox_Set_R3->setItemText(16, QApplication::translate("MainWindow", "16", nullptr));
        ComboBox_Set_R3->setItemText(17, QApplication::translate("MainWindow", "17", nullptr));
        ComboBox_Set_R3->setItemText(18, QApplication::translate("MainWindow", "18", nullptr));
        ComboBox_Set_R3->setItemText(19, QApplication::translate("MainWindow", "19", nullptr));
        ComboBox_Set_R3->setItemText(20, QApplication::translate("MainWindow", "20", nullptr));
        ComboBox_Set_R3->setItemText(21, QApplication::translate("MainWindow", "21", nullptr));
        ComboBox_Set_R3->setItemText(22, QApplication::translate("MainWindow", "22", nullptr));
        ComboBox_Set_R3->setItemText(23, QApplication::translate("MainWindow", "23", nullptr));
        ComboBox_Set_R3->setItemText(24, QApplication::translate("MainWindow", "24", nullptr));
        ComboBox_Set_R3->setItemText(25, QApplication::translate("MainWindow", "25", nullptr));

        ComboBox_Start_R3->setItemText(0, QApplication::translate("MainWindow", "A", nullptr));
        ComboBox_Start_R3->setItemText(1, QApplication::translate("MainWindow", "B", nullptr));
        ComboBox_Start_R3->setItemText(2, QApplication::translate("MainWindow", "C", nullptr));
        ComboBox_Start_R3->setItemText(3, QApplication::translate("MainWindow", "D", nullptr));
        ComboBox_Start_R3->setItemText(4, QApplication::translate("MainWindow", "E", nullptr));
        ComboBox_Start_R3->setItemText(5, QApplication::translate("MainWindow", "F", nullptr));
        ComboBox_Start_R3->setItemText(6, QApplication::translate("MainWindow", "G", nullptr));
        ComboBox_Start_R3->setItemText(7, QApplication::translate("MainWindow", "H", nullptr));
        ComboBox_Start_R3->setItemText(8, QApplication::translate("MainWindow", "I", nullptr));
        ComboBox_Start_R3->setItemText(9, QApplication::translate("MainWindow", "J", nullptr));
        ComboBox_Start_R3->setItemText(10, QApplication::translate("MainWindow", "K", nullptr));
        ComboBox_Start_R3->setItemText(11, QApplication::translate("MainWindow", "L", nullptr));
        ComboBox_Start_R3->setItemText(12, QApplication::translate("MainWindow", "M", nullptr));
        ComboBox_Start_R3->setItemText(13, QApplication::translate("MainWindow", "N", nullptr));
        ComboBox_Start_R3->setItemText(14, QApplication::translate("MainWindow", "O", nullptr));
        ComboBox_Start_R3->setItemText(15, QApplication::translate("MainWindow", "P", nullptr));
        ComboBox_Start_R3->setItemText(16, QApplication::translate("MainWindow", "Q", nullptr));
        ComboBox_Start_R3->setItemText(17, QApplication::translate("MainWindow", "R", nullptr));
        ComboBox_Start_R3->setItemText(18, QApplication::translate("MainWindow", "S", nullptr));
        ComboBox_Start_R3->setItemText(19, QApplication::translate("MainWindow", "T", nullptr));
        ComboBox_Start_R3->setItemText(20, QApplication::translate("MainWindow", "U", nullptr));
        ComboBox_Start_R3->setItemText(21, QApplication::translate("MainWindow", "V", nullptr));
        ComboBox_Start_R3->setItemText(22, QApplication::translate("MainWindow", "W", nullptr));
        ComboBox_Start_R3->setItemText(23, QApplication::translate("MainWindow", "X", nullptr));
        ComboBox_Start_R3->setItemText(24, QApplication::translate("MainWindow", "Y", nullptr));
        ComboBox_Start_R3->setItemText(25, QApplication::translate("MainWindow", "Z", nullptr));

        Label_Set_R3->setText(QApplication::translate("MainWindow", "Settaggio Rotore III", nullptr));
        ComboBox_R3->setItemText(0, QApplication::translate("MainWindow", "0", nullptr));
        ComboBox_R3->setItemText(1, QApplication::translate("MainWindow", "1", nullptr));
        ComboBox_R3->setItemText(2, QApplication::translate("MainWindow", "2", nullptr));
        ComboBox_R3->setItemText(3, QApplication::translate("MainWindow", "3", nullptr));

        ComboBox_R2->setItemText(0, QApplication::translate("MainWindow", "0", nullptr));
        ComboBox_R2->setItemText(1, QApplication::translate("MainWindow", "1", nullptr));
        ComboBox_R2->setItemText(2, QApplication::translate("MainWindow", "2", nullptr));
        ComboBox_R2->setItemText(3, QApplication::translate("MainWindow", "3", nullptr));

        ComboBox_R1->setItemText(0, QApplication::translate("MainWindow", "0", nullptr));
        ComboBox_R1->setItemText(1, QApplication::translate("MainWindow", "1", nullptr));
        ComboBox_R1->setItemText(2, QApplication::translate("MainWindow", "2", nullptr));
        ComboBox_R1->setItemText(3, QApplication::translate("MainWindow", "3", nullptr));

        Label_Set_R1_2->setText(QApplication::translate("MainWindow", "Posizione Rotore I ", nullptr));
        Label_Set_R1_3->setText(QApplication::translate("MainWindow", "Posizione Rotore II", nullptr));
        Label_Set_R1_4->setText(QApplication::translate("MainWindow", "Posizione Rotore III", nullptr));
        Btn_End_Cr->setText(QApplication::translate("MainWindow", "Inizio\n"
"cifratura", nullptr));
        Btn_Reset->setText(QApplication::translate("MainWindow", "Reset", nullptr));
        Btn_Save->setText(QApplication::translate("MainWindow", "Salva", nullptr));
        Btn_End_DeCr->setText(QApplication::translate("MainWindow", "Inzio\n"
"decifratura", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
